llc $1 \
--mtriple amdgcn-amd-amdhsa \
--mcpu=gfx908 \
--relocation-model=pic  \
--fp-contract=on \
--vectorize-loops \
--vectorize-slp \
--O3 \
--debugger-tune=gdb \
--amdgpu-internalize-symbols \
--addrsig
